export const GET_BANNER = 'GET_BANNER';
export const GET_HOTMOVIE = 'GET_HOTMOVIE';
export const GET_COMINGMOVIE = 'GET_COMINGMOVIE';

export const GET_FILM_COMINGSOON = 'GET_FILM_COMINGSOON';
export const GET_FILM_NOWPLAYING = 'GET_FILM_NOWPLAYING';

export const GET_DETAIL_FILM_BY_ID = 'GET_DETAIL_FILM_BY_ID';
export const GET_CINEMA_LIST = 'GET_CINEMA_LIST';

export const LOADING = 'LOADING';
